name: Publish

on:
  push:
    branches:
      - master

jobs:
  Publish:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip-ci]')"
    steps:
      - name: Git Identity
        run: |
          git config --global user.name '@langaads'
          git config --global user.email 'langaads@users.noreply.github.com'
          git remote set-url origin https://x-access-token:${GH_TOKEN}@github.com/$GITHUB_REPOSITORY
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
      - name: Checkout
        run: git checkout "${GITHUB_REF:11}"
      - name: Pull
        run: git pull
      - name: Install
        run: npm install
      - name: Build
        run: npm run build
      - name: Test
        run: npm run test
      - name: Publish
        if: success()
        run: |
          echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
          npx lerna publish from-git --yes
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
