name: Publish with Lerna

on:
  push:
    branches:
      - master

jobs:
  Publish_Workflow:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v1.0.0
      - name: Git Identity
        run: git config --global user.name '@${GH_USER}' && git config --global user.email '${GH_USER}@users.noreply.github.com' && git remote set-url origin https://x-access-token:${GH_TOKEN}@github.com/$GITHUB_REPOSITORY
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GH_USER: langaads
      - name: Prepare repository
        run: git checkout "${GITHUB_REF:11}"
      - name: Pulling
        run: git pull
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Test
        run: npm run test
      - name: Publish with Lerna
        run: npx lerna publish --yes --registry https://registry.npmjs.org/:_authToken=${NPM_TOKEN}
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
