name: Publish with Lerna

on:
  push:
    branches:
      - master

jobs:
  Publish_Workflow:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    steps:
      - name: Checkout repo
        uses: actions/checkout@v1.0.0
      - name: Git Identity
        run: |
          git config --global user.name '@langaads' 
          git config --global user.email 'langaads@users.noreply.github.com'
          git remote set-url origin https://x-access-token:${GH_TOKEN}@github.com/$GITHUB_REPOSITORY
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
      - name: Prepare repository
        run: git checkout "${GITHUB_REF:11}"
      - name: Pulling
        run: git pull
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Test
        run: npm run test
      - name: Publish with Lerna
        run: |
          echo "registry=//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc
          npx lerna publish --yes
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
