name: Release

on:
  release:
    types: [published]

jobs:
  Publish:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip-ci]')"
    steps:
      - name: Checkout
        uses: actions/checkout@v1.0.0

      - name: Install
        run: npm install --no-progress --no-audit

      - name: Build
        run: npm run build

      - name: Test
        run: npm run test

      - name: Publish
        if: success()
        run: |
          echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
          npx lerna publish from-git --yes
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

  Skip:
    runs-on: ubuntu-latest
    if: "contains(github.event.head_commit.message, '[skip-ci]')"
    steps:
      - name: Skip Feedback
        run: echo "Workflow skipped via commit message"
