name: Test

on:
  pull_request:
    branches:
      - master

jobs:
  Test:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip-ci]')"
    steps:
      - name: Checkout
        uses: actions/checkout@v1.0.0

      - name: Cache node_modules
        uses: actions/cache@v1
        id: cache_node_modules
        with:
          path: node_modules
          key: ${{ runner.os }}-v1-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-v1-node-${{ env.cache-name }}-

      - name: Install
        if: steps.cache_node_modules.outputs.cache-hit != 'true'
        run: npm install --no-progress --no-audit

      - name: Boostrap
        run: npm run boostrap

      - name: Test
        run: npm run ci

      - name: Coverage
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

  Skip:
    runs-on: ubuntu-latest
    if: "contains(github.event.head_commit.message, '[skip-ci]')"
    steps:
      - name: Skip Feedback
        run: echo "Workflow skipped via commit message"
