name: Publish

on:
  pull_request:
    branches:
      - master

jobs:
  Test:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip-ci]')"
    steps:
      - uses: actions/checkout@v1
      - name: Install
        run: npm install
      - name: Build
        run: npm run build
      - name: Test
        run: npm run test
